name: Swift

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

         # Install SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

         # Exceute SwiftLint
      - name: Run SwiftLint
        run: swiftlint lint --config .swiftlint.yml
        
        # Run tests on iPhone 14 Simulator with iOS 16.0
      - name: Run Tests on iPhone 14 Simulator (iOS 18.0)
        run: |
          xcodebuild test \
            -scheme 'PVPCPlanner' \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.0'

  unit_tests:
    name: Run Unit Tests
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Unit Tests on iPhone 14 Simulator (iOS 18.0)
        run: |
          xcodebuild test \
            -scheme 'PVPCPlanner' \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.0' \
            -only-testing:PVPCPlannerTests/UnitTests/ModelsTests \
            -only-testing:PVPCPlannerTests/UnitTests/PriceViewModelTest \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults

      - name: Generate Code Coverage Report
        run: |
          xcrun xccov view --report --json TestResults.xcresult > coverage.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  integration_tests:
    name: Run Integration Tests
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Integration Tests on iPhone 14 Simulator (iOS 18.0)
        run: |
          xcodebuild test \
            -scheme 'PVPCPlanner' \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.0' \
            -destination "platform=$platform,name=$device" \
            -only-testing:PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults   

      - name: Generate Code Coverage Report
        run: |
            xcrun xccov view --report --json TestResults.xcresult > coverage.json
  
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.json
            flags: unittests
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true
